spring.application.name=fnet3-pos
server.port=8080
fnet3.serial=8282
fnet3.username=opPruebaDev
fnet3.password=opPa$$
fnet3.url=https://test113.fidely.net/fnet3web/proxy/wsdl.php?v=01.89
fnet3.namespace=http://FidelyNET3_WS_01_89_00.Local
fnet3.serviceName=FNETWS_01_89_00_xService
