server.port=8080

pos.usuarios[0].username=opPruebaDev
pos.usuarios[0].password=$argon2id$v=19$m=16384,t=2,p=1$28d+J7CuDx6ohd5E0coLKw$F2IwPmLz6U9QblXQ6LpZlhWTw0P6aahUSW0ZnDUsutc
pos.usuarios[0].serial=8282

pos.usuarios[1].username=cajero1
pos.usuarios[1].password=$argon2id$v=19$m=16384,t=2,p=1$ktgeeHK6Bo9/ynVs6sMnvA$SfIrhqyXsRwfmsUPn/+eroVqNvmutxOFE1uJ3zPhnvM
pos.usuarios[1].serial=8282

pos.usuarios[2].username=supervisor
pos.usuarios[2].password=$argon2id$v=19$m=16384,t=2,p=1$hKphiC99rigAsQ87w/5LcQ$0I0XWgA0EEr09cgmyaxje8UQR7ZGo1cW7MaEWg7lj4A
pos.usuarios[2].serial=8282

fnet3.serial=8282
fnet3.username=opPruebaDev
fnet3.password=opPa$$
fnet3.url=https://test113.fidely.net/fnet3web/proxy/wsdl.php?v=01.89
fnet3.namespace=http://FidelyNET3_WS_01_89_00.Local
fnet3.serviceName=FNETWS_01_89_00_xService

jwt.secret=fnet3PosSecretKey2026SuperSeguraParaJWT1234567890ABCDEF
jwt.expiration=900000