
package com.pos.fnet3.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FNETWS_01_89_00_xService", targetNamespace = "http://FidelyNET3_WS_01_89_00.Local", wsdlLocation = "https://test113.fidely.net/fnet3web/proxy/wsdl.php?v=01.89")
public class FNETWS018900XService
    extends Service
{

    private static final URL FNETWS018900XSERVICE_WSDL_LOCATION;
    private static final WebServiceException FNETWS018900XSERVICE_EXCEPTION;
    private static final QName FNETWS018900XSERVICE_QNAME = new QName("http://FidelyNET3_WS_01_89_00.Local", "FNETWS_01_89_00_xService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://test113.fidely.net/fnet3web/proxy/wsdl.php?v=01.89");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FNETWS018900XSERVICE_WSDL_LOCATION = url;
        FNETWS018900XSERVICE_EXCEPTION = e;
    }

    public FNETWS018900XService() {
        super(__getWsdlLocation(), FNETWS018900XSERVICE_QNAME);
    }

    public FNETWS018900XService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FNETWS018900XSERVICE_QNAME, features);
    }

    public FNETWS018900XService(URL wsdlLocation) {
        super(wsdlLocation, FNETWS018900XSERVICE_QNAME);
    }

    public FNETWS018900XService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FNETWS018900XSERVICE_QNAME, features);
    }

    public FNETWS018900XService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FNETWS018900XService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FNETWS018900X
     */
    @WebEndpoint(name = "FNETWS_01_89_00_xSoap11")
    public FNETWS018900X getFNETWS018900XSoap11() {
        return super.getPort(new QName("http://FidelyNET3_WS_01_89_00.Local", "FNETWS_01_89_00_xSoap11"), FNETWS018900X.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FNETWS018900X
     */
    @WebEndpoint(name = "FNETWS_01_89_00_xSoap11")
    public FNETWS018900X getFNETWS018900XSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://FidelyNET3_WS_01_89_00.Local", "FNETWS_01_89_00_xSoap11"), FNETWS018900X.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FNETWS018900XSERVICE_EXCEPTION!= null) {
            throw FNETWS018900XSERVICE_EXCEPTION;
        }
        return FNETWS018900XSERVICE_WSDL_LOCATION;
    }

}
